### ISSUE TITLE
Log lines incorrectly appear in /var/log/apache2/error.log?

### ISSUE THREAD

**Issue by chrisroos** [freerange/webhooks#11] opened 2014-09-04 15:48 UTC
We're seeing entries in the Apache error.log that appear to be real log statements. Is this expected?

The entries look similar to:

    App 4905 stderr: <ip-addres> - - [31/Aug/2014 11:00:43] "HEAD /trello/events?token=<token>&task_url=https://harmonia.io/t/<task-id> " 200 2 0.0072

**Comment by floehopper** [comment] 2015-02-04 11:17
This is kind of a duplicate of #11. I'm going to mark it as such and close it.

**Closed by floehopper** 2015-02-04 11:17 UTC
Labels: duplicate

**Comment by floehopper** [comment] 2016-09-02 09:18
> I also wonder how the gofreerange.com Rack app is doing logging, but I've run out of energy to look into that now.

I've just had a quick look into this. It doesn't look as if the gofreerange.com Rack app has any specific logging setup, either in the Rack app or in the Apache config.
